name: cglm

on:
  workflow_dispatch:
  schedule:
     - cron: '*/30 1-8 * * *'
  watch:
    types: book

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          npm install got #tough-cooki
          from bs4 import BeautifulSoup
          import time
          import re
          import json
          import urllib.request
          import urllib.error
          import requests
          import ssl
      - name: '运行 【cglm】'
        #if: env.XL_HEADER
        run: |
          node test.py
        env:
          cglmheader: ${{ secrets.cglmheader }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
